/* Generated By:JavaCC: Do not edit this line. ScriptParserConstants.java */
package edu.curtin.terminalgriddemo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVENT = 5;
  /** RegularExpression Id. */
  int PLUGIN = 6;
  /** RegularExpression Id. */
  int SCRIPT = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int DATE = 9;
  /** RegularExpression Id. */
  int TIME = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"event\"",
    "\"plugin\"",
    "\"script\"",
    "<STRING>",
    "<DATE>",
    "<TIME>",
    "<INTEGER>",
  };

}
